-- ==============================================================================
-- CricUmpire Pro - Supabase PostgreSQL Schema & Realtime Setup
-- Paste this script into your Supabase Dashboard -> SQL Editor -> Run
-- ==============================================================================

-- 1. Create Matches Table (Stores match metadata, innings, player figures, FoW, and balls)
CREATE TABLE IF NOT EXISTS public.matches (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'live',
    match_data JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Create Audit Logs Table (Stores chronological scoring events, undos, and edits)
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id TEXT REFERENCES public.matches(id) ON DELETE CASCADE,
    user_name TEXT,
    action TEXT NOT NULL,
    action_type TEXT NOT NULL DEFAULT 'score',
    details TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Create Indexes for Fast Queries
CREATE INDEX IF NOT EXISTS idx_matches_status ON public.matches(status);
CREATE INDEX IF NOT EXISTS idx_matches_updated_at ON public.matches(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_match_id ON public.audit_logs(match_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON public.audit_logs(created_at DESC);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- 5. Create Permissive Access Policies (Allows Anon & Authenticated scorers to read & write)
DROP POLICY IF EXISTS "Allow public read matches" ON public.matches;
CREATE POLICY "Allow public read matches" 
ON public.matches FOR SELECT 
TO anon, authenticated 
USING (true);

DROP POLICY IF EXISTS "Allow public insert/update matches" ON public.matches;
CREATE POLICY "Allow public insert/update matches" 
ON public.matches FOR ALL 
TO anon, authenticated 
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read audit_logs" ON public.audit_logs;
CREATE POLICY "Allow public read audit_logs" 
ON public.audit_logs FOR SELECT 
TO anon, authenticated 
USING (true);

DROP POLICY IF EXISTS "Allow public insert audit_logs" ON public.audit_logs;
CREATE POLICY "Allow public insert audit_logs" 
ON public.audit_logs FOR ALL 
TO anon, authenticated 
USING (true)
WITH CHECK (true);

-- 6. Enable Supabase Realtime for Live Score Broadcasting
ALTER PUBLICATION supabase_realtime ADD TABLE public.matches;
ALTER PUBLICATION supabase_realtime ADD TABLE public.audit_logs;
